files:
  - source: /common/src/main/resources/lang/en.json
    translation: /common/src/main/resources/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        bg: bg
        bs: bs
        cs: cs
        de: de
        es-ES: es
        es-AR: es_AR
        fi: fi
        fr: fr
        he: he
        hi: hi
        hr: hr
        it: it
        ja: ja
        ko: ko
        nl: nl
        no: no
        pl: pl
        pt-BR: pt_BR
        pt-PT: pt
        ru: ru
        sr-CS: sr_CS
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh_CN
        zh-TW: zh_TW
        zh-HK: zh_HK
