name: ${name}
version: ${version}
main: ${group}.chunky.ChunkyBukkit
api-version: 1.13
folia-supported: true
softdepend: [dynmap, BlueMap, squaremap, WorldBorder]
load: POSTWORLD
authors: [${author}]
description: ${description}
website: https://www.spigotmc.org/resources/chunky.81534/
commands:
  chunky:
    description: Generates chunks
    aliases: [cy]
    permission: chunky.command
    usage: /chunky
permissions:
  chunky.command:
    default: op
  chunky.command.border:
    default: op
    children: [chunky.command]
  chunky.command.cancel:
    default: op
    children: [chunky.command]
  chunky.command.center:
    default: op
    children: [chunky.command]
  chunky.command.confirm:
    default: op
    children: [chunky.command]
  chunky.command.continue:
    default: op
    children: [chunky.command]
  chunky.command.corners:
    default: op
    children: [chunky.command]
  chunky.command.help:
    default: op
    children: [chunky.command]
  chunky.command.pattern:
    default: op
    children: [chunky.command]
  chunky.command.pause:
    default: op
    children: [chunky.command]
  chunky.command.progress:
    default: op
    children: [chunky.command]
  chunky.command.quiet:
    default: op
    children: [chunky.command]
  chunky.command.radius:
    default: op
    children: [chunky.command]
  chunky.command.reload:
    default: op
    children: [chunky.command]
  chunky.command.selection:
    default: op
    children: [chunky.command]
  chunky.command.shape:
    default: op
    children: [chunky.command]
  chunky.command.silent:
    default: op
    children: [chunky.command]
  chunky.command.spawn:
    default: op
    children: [chunky.command]
  chunky.command.start:
    default: op
    children: [chunky.command]
  chunky.command.trim:
    default: op
    children: [chunky.command]
  chunky.command.worldborder:
    default: op
    children: [chunky.command]
  chunky.command.world:
    default: op
    children: [chunky.command]
  chunky.chunky:
    default: false
    children:
      - chunky.command
      - chunky.command.cancel
      - chunky.command.center
      - chunky.command.confirm
      - chunky.command.continue
      - chunky.command.corners
      - chunky.command.help
      - chunky.command.pattern
      - chunky.command.pause
      - chunky.command.progress
      - chunky.command.quiet
      - chunky.command.radius
      - chunky.command.reload
      - chunky.command.selection
      - chunky.command.shape
      - chunky.command.silent
      - chunky.command.spawn
      - chunky.command.start
      - chunky.command.worldborder
      - chunky.command.world
