name: Build Chunky
on: [ push, pull_request ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build
      - name: Upload Bukkit
        uses: actions/upload-artifact@v2
        with:
          name: Bukkit
          path: "bukkit/build/libs/Chunky-*.jar"
      - name: Upload Fabric
        uses: actions/upload-artifact@v2
        with:
          name: Fabric
          path: "fabric/build/libs/Chunky-*.jar"
      - name: Upload Forge
        uses: actions/upload-artifact@v2
        with:
          name: Forge
          path: "forge/build/libs/Chunky-*.jar"
      - name: Upload Sponge
        uses: actions/upload-artifact@v2
        with:
          name: Sponge
          path: "sponge/build/libs/Chunky-*.jar"
